server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: PsLwo
  jpa:
    hibernate:
      ddl-auto: update # Позже лучше использовать миграции через Flyway вместо ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: invoiceflow

logging:
  level:
    root: info
    com:
      invoiceflow: debug

jwt:
  secret: TYxAOQtVgzvopjIdplDpdsL/vsbFBT9fSEs6EWckSPg=
  expiration: 86400000